# frozen_string_literal: true

source "https://rubygems.org"

# FunApi framework
gem "funapi", github: "gafemoyano/funapi"

# Database
gem "sequel", "~> 5.75"
gem "sqlite3", "~> 1.7"

# Server
gem "falcon", "~> 0.47"
