# frozen_string_literal: true

source "https://rubygems.org"

# FunApi framework
gem "funapi", github: "gafemoyano/funapi"

# Database
gem "db", "~> 0.14"
gem "db-postgres", "~> 0.9"

# Server
gem "falcon", "~> 0.47"
